apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project2-pvc-tassioalmeida
  namespace: tassioalmeida
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      namespace: tassioalmeida
  storageClassName: default-storage-class-tassioalmeida
